name: CI for macOS

on:
  pull_request:
    branches:
      - master
  push:

jobs:
  macos-build-and-test:
    runs-on: macos-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: ./ci/install_macos_dependencies.sh
    - name: build
      run: |
        mkdir build && cd build
        cmake ..
        make
    - name: unit tests
      run: |
        cd build
        ctest -j2 -V -E inttest.*
    - name: regression tests
      run: |
        cd build
        ctest --stop-on-failure -j2 -V -R inttest.*
