name: CI for macOS

on:
  pull_request:
    branches:
      - master
  push:

jobs:
  macos-build-and-test:
    runs-on: macos-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: ./ci/install_macos_dependencies.sh
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
